# Generated by Django 2.0.5 on 2019-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0002_contact")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="defaultUserImg.jpg", upload_to="users/%Y/%m/%d/"
            ),
        )
    ]
