# Generated by Django 2.0.5 on 2019-02-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="braintree_id",
            field=models.CharField(blank=True, max_length=50),
        )
    ]
