# Generated by Django 2.0.5 on 2019-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0002_orderitem_price")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="braintree_id",
            field=models.CharField(blank=True, max_length=150),
        )
    ]
